"""add knowledge_documents table

Revision ID: 092c81b1003a
Revises: ba5ee13dac3e
Create Date: 2026-06-02 17:49:50.167231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092c81b1003a'
down_revision = 'ba5ee13dac3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
